name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - architecture: aarch64
            image: ghcr.io/home-assistant/aarch64-base:3.15
            platform: linux/arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        run: docker buildx create --use

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image for {{ matrix.architecture }}
        run: |
          docker buildx build --pull --platform='linux/arm64' --build-arg 'BUILD_FROM={{ matrix.image }}' --tag '${{ secrets.DOCKERHUB_USERNAME }}/my-image:{{ matrix.architecture }}' --file 'Dockerfile' .

      - name: Push Docker image for {{ matrix.architecture }}
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-image:{{ matrix.architecture }}