name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - architecture: aarch64
            image: arm64v8/alpine:3.15
            platform: linux/arm64
          - architecture: amd64
            image: alpine:3.15
            platform: linux/amd64
          - architecture: armhf
            image: arm32v6/alpine:3.15
            platform: linux/arm/v6
          - architecture: armv7
            image: arm32v7/alpine:3.15
            platform: linux/arm/v7
          - architecture: i386
            image: i386/alpine:3.15
            platform: linux/386
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        run: docker buildx create --use

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image for {{ matrix.architecture }}
        run: |
          docker buildx build \
            --platform "${{ matrix.platform }}" \
            --build-arg "BUILD_FROM=${{ matrix.image }}" \
            --tag "${{ secrets.DOCKER_USERNAME }}/my-image:${{ matrix.architecture }}" \
            --pull \
            --push \
            .