name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - architecture: aarch64
            image: ghcr.io/home-assistant/aarch64-base:3.15
            platform: linux/arm64
          - architecture: amd64
            image: ghcr.io/home-assistant/amd64-base:3.15
            platform: linux/amd64
          - architecture: armhf
            image: ghcr.io/home-assistant/armhf-base:3.15
            platform: linux/arm/v6
          - architecture: armv7
            image: ghcr.io/home-assistant/armv7-base:3.15
            platform: linux/arm/v7
          - architecture: i386
            image: ghcr.io/home-assistant/i386-base:3.15
            platform: linux/386
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        run: docker buildx create --use

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image for {{ matrix.architecture }}
        run: |
          docker buildx build --pull --platform={{ matrix.platform }} --build-arg BUILD_FROM={{ matrix.image }} --tag ${{ secrets.DOCKERHUB_USERNAME }}/my-image:{{ matrix.architecture }} .

      - name: Push Docker image for {{ matrix.architecture }}
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-image:{{ matrix.architecture }}